### ISSUE TITLE
Better support for empty post_content

### ISSUE THREAD

**Issue by shawfactor** [pfefferle/wordpress-webmention#332]
This plugin attempts to run on posts where the content is empty, thus creating errors eg:

Uncaught ValueError: DOMDocument::loadHTML(): Argument #1 ($source) must not be empty in /*******/wp-content/plugins/webmention/includes/functions.php:364

It is now big deal but can the logic be improved for situations where the post_cintent will be empty? beter to account for this and not run the process and not create errors I think?

**Comment by zerosonesfun** [comment]
I think what I see in my error log now relates to this. I do have a unique custom post type which could sometimes create a blank post (not really, but kind of... long story). If that is what's happening, then some kind of `if post_content == null` addition to the code would be great.

`[07-Apr-2023 17:18:37 UTC] PHP Warning:  Attempt to read property "post_content" on null in /wp-content/plugins/webmention/includes/class-sender.php on line 163
[07-Apr-2023 17:18:37 UTC] PHP Fatal error:  Uncaught TypeError: DOMXPath::__construct(): Argument #1 ($document) must be of type DOMDocument, WP_Error given in /wp-content/plugins/webmention/includes/functions.php:283
Stack trace:
#0 /wp-content/plugins/webmention/includes/functions.php(283): DOMXPath->__construct()
#1 /wp-content/plugins/webmention/includes/class-sender.php(163): webmention_extract_urls()
#2 /wp-includes/class-wp-hook.php(308): Webmention\Sender::send_webmentions()
#3 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /wp-includes/plugin.php(565): WP_Hook->do_action()
#5 /wp-cron.php(188): do_action_ref_array()
#6 {main}
  thrown in /wp-content/plugins/webmention/includes/functions.php on line 283`

**Comment by pfefferle** [comment]
Not exactly. In this case not `post_content` is null, but `$post`. That means `get_post()` returns `null` 😳

**Comment by dshanske** [comment]
It should..post is a post object..not a post object of type post

**Comment by zerosonesfun** [comment]
Ok, never mind about my comment. Sorry. I don't think it's an issue. I can't seem to reproduce it now.

**Comment by shawfactor** [comment]
I see the same issue after publishing non public cpts, although I agree it is a seperate one

**Comment by zerosonesfun** [comment]
> I see the same issue after publishing non public cpts, although I agree it is a seperate one

Thanks! Sometimes these things are so odd. I thought maybe it wasn’t an issue after all. Because errors stopped being logged for a moment. But, now that you left this comment, that’s exactly what I was doing. Publishing a private custom post type.
