### ISSUE TITLE
mb_convert_encoding deprecated

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-webmention#382]
mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in webmention/includes/class-response.php on line 160

**Comment by edent** [comment]
Just got this error:

```
PHP Fatal error:  Uncaught ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) must specify at least one encoding in /wp-content/plugins/webmention/includes/class-response.php:160
Stack trace:
#0 /wp-content/plugins/webmention/includes/class-response.php(160): mb_convert_encoding()
#1 /wp-content/plugins/webmention/includes/class-discovery.php(187): Webmention\Response->get_dom_document()
#2 /wp-content/plugins/webmention/includes/functions.php(259): Webmention\Discovery::discover_endpoint()
#3 /wp-content/plugins/webmention/includes/class-sender.php(104): webmention_discover_endpoint()
#4 /wp-content/plugins/webmention/includes/class-sender.php(181): Webmention\Sender::send_webmention()
#5 /wp-content/plugins/webmention/includes/class-sender.php(299): Webmention\Sender::send_webmentions()
#6 /wp-includes/class-wp-hook.php(310): Webmention\Sender::do_webmentions()
#7 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#8 /wp-includes/plugin.php(565): WP_Hook->do_action()
#9 /wp-cron.php(191): do_action_ref_array()
#10 {main}
  thrown in /wp-content/plugins/webmention/includes/class-response.php on line 160
```

**Comment by edent** [comment]
Still seeing this.

`PHP Deprecated:  mb_convert_encoding(): Handling HTML entities via mbstring is deprecated; use htmlspecialchars, htmlentities, or mb_encode_numericentity/mb_decode_numericentity instead in /wp-content/plugins/webmention/includes/class-response.php on line 183`

https://github.com/pfefferle/wordpress-webmention/blob/57ecf6d4fc5e6a2c2ec9b49c707332f2095fd726/includes/class-response.php#L181-L184
