### ISSUE TITLE
Timezone issue causes exception

### ISSUE THREAD

**Issue by edent** [pfefferle/wordpress-webmention#415]
I'm trying to submit a webmention from @bekopharm  - https://beko.famkos.net/2023/08/28/2334321/

This is the error I see:

```
[28-Aug-2023 07:31:07 UTC] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /wp-content/plugins/webmention/includes/Handler/class-wp.php:164
Stack trace:
#0 /wp-content/plugins/webmention/includes/Handler/class-wp.php(164): DateTimeZone->__construct()
#1 /wp-content/plugins/webmention/includes/Handler/class-wp.php(66): Webmention\Handler\WP->parse_site_json()
#2 /wp-content/plugins/webmention/includes/class-handler.php(84): Webmention\Handler\WP->parse()
#3 /wp-content/plugins/webmention/includes/class-receiver.php(620): Webmention\Handler->parse_aggregated()
#4 /wp-includes/class-wp-hook.php(310): Webmention\Receiver::default_commentdata()
#5 /wp-includes/plugin.php(205): WP_Hook->apply_filters()
#6 /wp-content/plugins/webmention/includes/class-receiver.php(330): apply_filters()
#7 /wp-includes/rest-api/class-wp-rest-server.php(1188): Webmention\Receiver::post()
#8 /wp-includes/rest-api/class-wp-rest-server.php(1035): WP_REST_Server->respond_to_request()
#9 /wp-includes/rest-api/class-wp-rest-server.php(447): WP_REST_Server->dispatch()
#10 /wp-includes/rest-api.php(418): WP_REST_Server->serve_request()
#11 /wp-includes/class-wp-hook.php(310): rest_api_loaded()
#12 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#13 /wp-includes/plugin.php(565): WP_Hook->do_action()
#14 /wp-includes/class-wp.php(398): do_action_ref_array()
#15 /wp-includes/class-wp.php(779): WP->parse_request()
#16 /wp-includes/functions.php(1335): WP->main()
#17 /wp-blog-header.php(16): wp()
#18 /index.php(17): require('...')
#19 {main}
  thrown in /wp-content/plugins/webmention/includes/Handler/class-wp.php on line 164
```

**Comment by bekopharm** [comment]
This is what apparently can be found in the DOM: https://php.microformats.io/?url=https%3A%2F%2Fbeko.famkos.net%2F2023%2F08%2F28%2F2334321%2F

published: `2023-08-28T09:29:48+02:00`

I checked the source and apparently the Webmention plugin tries to parse from JSON: `$site_json['timezone'] = new DateTimeZone( $site_json['timezone_string'] );`

So I fetched the article with curl:

> curl --header "Content-Type: application/json"  https://beko.famkos.net/wp-json/wp/v2/posts/15628775

```
  "modified": "2023-08-28T09:29:48",
  "modified_gmt": "2023-08-28T07:29:48",
```

There is no `timezone_string`.

**Comment by bekopharm** [comment]
That was fast :+1: 

For what it's worth I changed the Time zone setting in WordPress to a city. It was on "UTC". Apparently that helped also :shrug:
