### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string

### ISSUE THREAD

**Issue by cybeardjm** [pfefferle/wordpress-webmention#458]
From my PHP error log, have plenty of them... every minute or so... from both WP blogs

[30-Jan-2024 16:20:54 UTC] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/Handler/class-mf2.php:432
Stack trace:
#0 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/Handler/class-mf2.php(472): Webmention\Handler\MF2->find_representative_item()
#1 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/Handler/class-mf2.php(47): Webmention\Handler\MF2->get_representative_item()
#2 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-handler.php(84): Webmention\Handler\MF2->parse()
#3 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-receiver.php(657): Webmention\Handler->parse_aggregated()
#4 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/class-wp-hook.php(324): Webmention\Receiver::default_commentdata()
#5 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#6 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/class-receiver.php(329): apply_filters()
#7 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/rest-api/class-wp-rest-server.php(1193): Webmention\Receiver::post()
#8 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server->respond_to_request()
#9 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server->dispatch()
#10 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/rest-api.php(424): WP_REST_Server->serve_request()
#11 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/class-wp-hook.php(324): rest_api_loaded()
#12 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#13 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#14 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/class-wp.php(418): do_action_ref_array()
#15 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/class-wp.php(813): WP->parse_request()
#16 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-includes/functions.php(1336): WP->main()
#17 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-blog-header.php(16): wp()
#18 /srv/data/web/vhosts/amf.didiermary.fr/htdocs/index.php(17): require('...')
#19 {main}
  thrown in /srv/data/web/vhosts/amf.didiermary.fr/htdocs/wp-content/plugins/webmention/includes/Handler/class-mf2.php on line 432

**Comment by cybeardjm** [comment]
No news on this @pfefferle ? I've got MegaBytes after MegaBytes of this error in my log...
