### ISSUE TITLE
Warning: Undefined array key "format" in ~/wp-content/plugins/webmention/includes/class-comment-walker.php on line 121

### ISSUE THREAD

**Issue by jeremycherfas** [pfefferle/wordpress-webmention#499]
That's it. A warning that prevents Comments displaying. Grateful for any help to resolve this.

Using ClassicPress 2.2.0 on a local development site

Stack trace:

```
Fatal error: Uncaught Error: Call to undefined method Webmention\Comment_Walker::comment() in /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/wp-content/plugins/webmention/includes/class-comment-walker.php:127 Stack trace: #0 /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/wp-includes/class-wp-walker.php(147): Webmention\Comment_Walker->start_el('', Object(WP_Comment), 1, Array) #1 /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/wp-includes/class-walker-comment.php(140): Walker->display_element(Object(WP_Comment), Array, '5', 0, Array, '') #2 /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/wp-includes/class-wp-walker.php(390): Walker_Comment->display_element(Object(WP_Comment), Array, '5', 0, Array, '') #3 /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/wp-includes/comment-template.php(2414): Walker->paged_walk(Array, '5', 0, 0, Array) #4 /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/wp-content/themes/etp/comments.php(53): wp_list_comments(Array) #5 /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/wp-includes/comment-template.php(1664): require('/Users/jeremych...') #6 /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/wp-content/themes/etp/single.php(49): comments_template() #7 /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/wp-includes/template-loader.php(108): include('/Users/jeremych...') #8 /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/wp-blog-header.php(19): require_once('/Users/jeremych...') #9 /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/index.php(17): require('/Users/jeremych...') #10 {main} thrown in /Users/jeremycherfas/sites/MAMP-htdocs/ClassicPress-release-1.5.2/wp-content/plugins/webmention/includes/class-comment-walker.php on line 127
```

**Comment by dshanske** [comment]
I already fixed this in dev  And filed a ClassicPress issue

**Comment by dshanske** [comment]
See #494

**Comment by pfefferle** [comment]
let's close this then. will be fixed with the next version!
